apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-k8
  template:
    metadata:
      labels:
        app: my-app-k8
    spec:
      containers:
        - name: app
          image: parane/hello-world
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090