apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app-k8
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8090
      nodePort: 30100
